# IMPORTANT: Changes to this file will be applied to all environments, even if you deploy dev only.

---
apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: rooster-frontend
  labels:
    p6m.dev/domain: 'ybor-technologies'
    p6m.dev/app: 'rooster-frontend'
spec:
  autoscaling:
    enabled: true
  deployment:
    image: 'rooster-frontend-server:latest' # Set to a digest in the .platform repo patch
    ports:
      - protocol: http
        port: 3000
    readinessProbe:
      port: 3000
      path: /
  networking:
    ingress:
      enabled: true
      oidc: true # OAuth2 Proxy is enabled by default
      path: /
      hostnames: [] # This is set in the patch files per environment
